(function () {
  function S(overrides) {
    return Object.assign(
      {
        everyday: 0,
        school: 0,
        work: 0,
        photo: 0,
        code: 0,
        film: 0,
        fitness: 0,
        calls: 0,
        entertainment: 0,
        notes: 0,
        drawing: 0,
        desk: 0,
        mobile: 0,
        mix: 0,
        camera: 0,
        battery: 0,
        power: 0,
        portability: 0,
        display: 0,
        health: 0,
        pencil: 0,
        cellular: 0,
        large: 0,
        compact: 0,
        anc: 0,
        ports: 0,
        outdoor: 0,
        overear: 0,
        entry: 0,
      },
      overrides
    );
  }

  const buy = {
    mac: "https://www.apple.com/shop/buy-mac",
    iphone: "https://www.apple.com/shop/buy-iphone",
    ipad: "https://www.apple.com/shop/buy-ipad",
    watch: "https://www.apple.com/shop/buy-watch",
    airpods: "https://www.apple.com/shop/buy-airpods",
    tv: "https://www.apple.com/shop/buy-tv",
  };

  const products = [
    {
      id: "macbook-neo",
      name: "MacBook Neo",
      chip: "A18 Pro",
      category: "mac",
      theme: "light",
      kind: "macbook",
      tagline: "Everyday power. A friendlier price.",
      pitch:
        "A Mac for class, browsing, writing, and everything that does not need a pro chip.",
      chooseIf: "You want a real Mac laptop and you want to spend as little as possible.",
      price: 699,
      finishes: [
        { name: "Silver", hex: "#d7d8dc" },
        { name: "Blue", hex: "#8eb4d4" },
        { name: "Pink", hex: "#e7c2c7" },
        { name: "Yellow", hex: "#f0e0a8" },
      ],
      specs: [
        ["Chip", "A18 Pro"],
        ["Design", "Fanless laptop"],
        ["Best for", "School and everyday"],
        ["Starts at", "$699"],
      ],
      scores: S({
        everyday: 8,
        school: 9,
        work: 5,
        photo: 4,
        code: 3,
        film: 2,
        notes: 8,
        entertainment: 7,
        calls: 3,
        desk: 6,
        mobile: 9,
        mix: 8,
        camera: 4,
        battery: 8,
        power: 4,
        portability: 9,
        display: 6,
        large: 3,
        compact: 8,
        ports: 4,
        entry: 9,
      }),
      buy: buy.mac,
    },
    {
      id: "mba-13",
      name: "13-inch MacBook Air",
      chip: "M5",
      category: "mac",
      theme: "light",
      kind: "macbook",
      tagline: "Now supercharged by M5.",
      pitch:
        "The Mac most people should buy. Light, quiet, and quick enough for school, work, and photos.",
      chooseIf: "You want one laptop that handles almost everything and disappears in a bag.",
      price: 1299,
      finishes: [
        { name: "Sky Blue", hex: "#b7c9d9" },
        { name: "Silver", hex: "#d8d8dc" },
        { name: "Starlight", hex: "#e8dccb" },
        { name: "Midnight", hex: "#2b3038" },
      ],
      specs: [
        ["Chip", "Apple M5"],
        ["Display", "13.6-inch Liquid Retina"],
        ["Design", "Fanless aluminum"],
        ["Best for", "Everyday and work"],
      ],
      scores: S({
        everyday: 9,
        school: 10,
        work: 8,
        photo: 7,
        code: 7,
        film: 4,
        notes: 8,
        entertainment: 8,
        calls: 4,
        desk: 7,
        mobile: 10,
        mix: 9,
        camera: 6,
        battery: 9,
        power: 7,
        portability: 10,
        display: 8,
        large: 4,
        compact: 8,
        ports: 5,
        entry: 5,
      }),
      buy: buy.mac,
    },
    {
      id: "mba-15",
      name: "15-inch MacBook Air",
      chip: "M5",
      category: "mac",
      theme: "light",
      kind: "macbook",
      tagline: "More room. Same Air feeling.",
      pitch:
        "The thin Air, with a larger Liquid Retina display when you want more space to work.",
      chooseIf: "You like the Air, and you want a bigger screen without moving up to a Pro.",
      price: 1499,
      finishes: [
        { name: "Sky Blue", hex: "#b7c9d9" },
        { name: "Silver", hex: "#d8d8dc" },
        { name: "Starlight", hex: "#e8dccb" },
        { name: "Midnight", hex: "#2b3038" },
      ],
      specs: [
        ["Chip", "Apple M5"],
        ["Display", "15.3-inch Liquid Retina"],
        ["Design", "Fanless aluminum"],
        ["Best for", "Bigger-screen everyday"],
      ],
      scores: S({
        everyday: 8,
        school: 8,
        work: 8,
        photo: 7,
        code: 7,
        film: 5,
        notes: 8,
        entertainment: 8,
        desk: 8,
        mobile: 8,
        mix: 9,
        camera: 6,
        battery: 9,
        power: 7,
        portability: 7,
        display: 9,
        large: 8,
        compact: 4,
        ports: 5,
        entry: 4,
      }),
      buy: buy.mac,
    },
    {
      id: "mbp-14",
      name: "14-inch MacBook Pro",
      chip: "M5",
      category: "mac",
      theme: "dark",
      kind: "macbook",
      tagline: "Pro performance. Portable size.",
      pitch:
        "A pro laptop for coding, photo editing, and long work days — without jumping to the Max chips.",
      chooseIf: "You want a Pro display and ports, and M5 is enough for the work you do.",
      price: 1999,
      finishes: [
        { name: "Space Black", hex: "#2a2b2e" },
        { name: "Silver", hex: "#d5d6da" },
      ],
      specs: [
        ["Chip", "Apple M5"],
        ["Display", "14-inch Liquid Retina XDR"],
        ["Design", "Pro ports and cooling"],
        ["Best for", "Work and creation"],
      ],
      scores: S({
        everyday: 6,
        school: 6,
        work: 9,
        photo: 8,
        code: 8,
        film: 7,
        notes: 6,
        entertainment: 7,
        desk: 8,
        mobile: 8,
        mix: 9,
        camera: 7,
        battery: 8,
        power: 8,
        portability: 7,
        display: 9,
        large: 6,
        compact: 5,
        ports: 8,
        entry: 2,
      }),
      buy: buy.mac,
    },
    {
      id: "mbp-14-pro",
      name: "14-inch MacBook Pro",
      chip: "M5 Pro",
      category: "mac",
      theme: "dark",
      kind: "macbook",
      tagline: "M5 Pro. For serious projects.",
      pitch:
        "The portable pro pick when video, code, and design are the job — not a side project.",
      chooseIf: "You edit often and want more GPU and CPU than the base 14-inch Pro.",
      price: 2499,
      finishes: [
        { name: "Space Black", hex: "#2a2b2e" },
        { name: "Silver", hex: "#d5d6da" },
      ],
      specs: [
        ["Chip", "Apple M5 Pro"],
        ["Display", "14-inch Liquid Retina XDR"],
        ["Design", "Pro cooling and ports"],
        ["Best for", "Video, code, design"],
      ],
      scores: S({
        everyday: 5,
        school: 4,
        work: 9,
        photo: 9,
        code: 9,
        film: 9,
        desk: 8,
        mobile: 7,
        mix: 8,
        camera: 7,
        battery: 8,
        power: 9,
        portability: 6,
        display: 9,
        large: 6,
        compact: 4,
        ports: 9,
        entry: 1,
      }),
      buy: buy.mac,
    },
    {
      id: "mbp-16-pro",
      name: "16-inch MacBook Pro",
      chip: "M5 Pro",
      category: "mac",
      theme: "dark",
      kind: "macbook",
      tagline: "A bigger canvas for pro work.",
      pitch:
        "The large pro laptop when you want screen space and M5 Pro performance in one bag.",
      chooseIf: "You want the biggest MacBook display and you still need to carry it.",
      price: 2999,
      finishes: [
        { name: "Space Black", hex: "#2a2b2e" },
        { name: "Silver", hex: "#d5d6da" },
      ],
      specs: [
        ["Chip", "Apple M5 Pro"],
        ["Display", "16-inch Liquid Retina XDR"],
        ["Design", "Largest MacBook Pro"],
        ["Best for", "Pro work on the go"],
      ],
      scores: S({
        everyday: 4,
        school: 3,
        work: 8,
        photo: 8,
        code: 9,
        film: 9,
        desk: 8,
        mobile: 6,
        mix: 7,
        battery: 8,
        power: 9,
        portability: 5,
        display: 10,
        large: 9,
        compact: 2,
        ports: 9,
        entry: 1,
      }),
      buy: buy.mac,
    },
    {
      id: "mbp-16-max",
      name: "16-inch MacBook Pro",
      chip: "M5 Max",
      category: "mac",
      theme: "dark",
      kind: "macbook",
      tagline: "Maximum chip. Maximum screen.",
      pitch:
        "For film, 3D, and heavy exports when the laptop itself has to be the workstation.",
      chooseIf: "You need M5 Max performance and you refuse to leave the work on a desktop.",
      price: 4399,
      finishes: [
        { name: "Space Black", hex: "#2a2b2e" },
        { name: "Silver", hex: "#d5d6da" },
      ],
      specs: [
        ["Chip", "Apple M5 Max"],
        ["Display", "16-inch Liquid Retina XDR"],
        ["Design", "Highest-end MacBook Pro"],
        ["Best for", "Film and 3D"],
      ],
      scores: S({
        everyday: 3,
        school: 2,
        work: 8,
        photo: 9,
        code: 9,
        film: 10,
        desk: 8,
        mobile: 5,
        mix: 6,
        battery: 7,
        power: 10,
        portability: 4,
        display: 10,
        large: 9,
        compact: 1,
        ports: 9,
      }),
      buy: buy.mac,
    },
    {
      id: "imac",
      name: "24-inch iMac",
      chip: "M4",
      category: "mac",
      theme: "light",
      kind: "imac",
      tagline: "Colorful. Complete. On your desk.",
      pitch:
        "An all-in-one for a desk that should look good and handle everyday work, school, and photos.",
      chooseIf: "You want a beautiful display and a Mac that lives in one place.",
      price: 1299,
      finishes: [
        { name: "Blue", hex: "#6f9cb8" },
        { name: "Green", hex: "#a8c3b0" },
        { name: "Pink", hex: "#e4b8be" },
        { name: "Silver", hex: "#d5d6da" },
        { name: "Yellow", hex: "#f3e2a4" },
        { name: "Orange", hex: "#e89a63" },
        { name: "Purple", hex: "#b9a6d6" },
      ],
      specs: [
        ["Chip", "Apple M4"],
        ["Display", "24-inch 4.5K Retina"],
        ["Design", "All-in-one"],
        ["Best for", "Home and office desk"],
      ],
      scores: S({
        everyday: 8,
        school: 8,
        work: 7,
        photo: 7,
        code: 6,
        film: 5,
        notes: 7,
        entertainment: 8,
        desk: 10,
        mobile: 1,
        mix: 3,
        camera: 5,
        battery: 0,
        power: 6,
        portability: 1,
        display: 10,
        large: 8,
        compact: 2,
        ports: 5,
        entry: 4,
      }),
      buy: buy.mac,
    },
    {
      id: "mac-mini",
      name: "Mac mini",
      chip: "M6",
      category: "mac",
      theme: "light",
      kind: "mini",
      tagline: "Now with M6.",
      pitch:
        "A small desktop with serious speed. Bring your own display, keyboard, and trackpad.",
      chooseIf: "You already have a monitor and you want the most Mac for the least money.",
      price: 899,
      finishes: [{ name: "Silver", hex: "#d8d8dc" }],
      specs: [
        ["Chip", "Apple M6"],
        ["Design", "Compact desktop"],
        ["Display", "Sold separately"],
        ["Best for", "Desk setups"],
      ],
      scores: S({
        everyday: 7,
        school: 7,
        work: 8,
        photo: 6,
        code: 8,
        film: 6,
        entertainment: 7,
        desk: 10,
        mobile: 1,
        mix: 3,
        power: 8,
        portability: 2,
        display: 2,
        large: 2,
        compact: 7,
        ports: 8,
        entry: 7,
        battery: 0,
      }),
      buy: buy.mac,
    },
    {
      id: "mac-mini-pro",
      name: "Mac mini",
      chip: "M5 Pro",
      category: "mac",
      theme: "light",
      kind: "mini",
      tagline: "M5 Pro. Pro work, mini footprint.",
      pitch:
        "Deskside power for video and development, without a tower. Display sold separately.",
      chooseIf: "You want pro-level speed on a desk and you do not need a built-in screen.",
      price: 1699,
      finishes: [{ name: "Silver", hex: "#d8d8dc" }],
      specs: [
        ["Chip", "Apple M5 Pro"],
        ["Design", "Compact desktop"],
        ["Display", "Sold separately"],
        ["Best for", "Pro desk work"],
      ],
      scores: S({
        everyday: 5,
        school: 4,
        work: 8,
        photo: 8,
        code: 9,
        film: 8,
        desk: 10,
        mobile: 1,
        mix: 3,
        power: 9,
        portability: 2,
        display: 2,
        compact: 6,
        ports: 9,
        battery: 0,
      }),
      buy: buy.mac,
    },
    {
      id: "mac-studio",
      name: "Mac Studio",
      chip: "M5 Max",
      category: "mac",
      theme: "dark",
      kind: "studio",
      tagline: "Workstation performance. On the desk.",
      pitch:
        "For film, 3D, and always-on pro work when the computer never needs to leave the studio.",
      chooseIf: "Your heaviest work stays at a desk and you want Max-class performance.",
      price: 2499,
      finishes: [{ name: "Silver", hex: "#c8c8cc" }],
      specs: [
        ["Chip", "Apple M5 Max"],
        ["Design", "Desktop workstation"],
        ["Display", "Sold separately"],
        ["Best for", "Studios and heavy exports"],
      ],
      scores: S({
        everyday: 3,
        school: 2,
        work: 8,
        photo: 8,
        code: 9,
        film: 10,
        desk: 10,
        mobile: 1,
        mix: 2,
        power: 10,
        portability: 1,
        display: 2,
        ports: 10,
        compact: 3,
        battery: 0,
      }),
      buy: buy.mac,
    },
    {
      id: "iphone-17e",
      name: "iPhone 17e",
      chip: "A19",
      category: "iphone",
      theme: "light",
      kind: "iphone",
      tagline: "A lot of iPhone. Less to spend.",
      pitch:
        "The iPhone to buy when you want the essentials — messages, photos, and all-day use — at the lowest price.",
      chooseIf: "You want an iPhone and keeping the price down matters more than a pro camera.",
      price: 599,
      finishes: [
        { name: "Black", hex: "#1d1f22" },
        { name: "White", hex: "#f2f1ed" },
        { name: "Pink", hex: "#f0c9cf" },
      ],
      specs: [
        ["Chip", "A19"],
        ["Display", "Super Retina XDR"],
        ["Camera", "Advanced dual-camera system"],
        ["Best for", "Everyday"],
      ],
      scores: S({
        everyday: 9,
        school: 8,
        work: 5,
        photo: 6,
        entertainment: 7,
        calls: 8,
        notes: 4,
        fitness: 3,
        desk: 3,
        mobile: 9,
        mix: 8,
        camera: 5,
        battery: 7,
        power: 5,
        portability: 8,
        display: 6,
        large: 4,
        compact: 8,
        cellular: 9,
        entry: 9,
      }),
      buy: buy.iphone,
    },
    {
      id: "iphone-17",
      name: "iPhone 17",
      chip: "A19",
      category: "iphone",
      theme: "light",
      kind: "iphone",
      tagline: "The iPhone for most people.",
      pitch:
        "A bright display, a strong camera, and battery life that covers a normal day — without the Pro price.",
      chooseIf: "You want the balanced iPhone and you do not need the pro camera system.",
      price: 799,
      finishes: [
        { name: "Black", hex: "#222326" },
        { name: "Lavender", hex: "#d5cbe3" },
        { name: "Sage", hex: "#c5d2c4" },
        { name: "Blue", hex: "#b7cfe2" },
        { name: "White", hex: "#f4f2ee" },
      ],
      specs: [
        ["Chip", "A19"],
        ["Display", "Super Retina XDR"],
        ["Camera", "Dual-camera system"],
        ["Best for", "Everyday photos and life"],
      ],
      scores: S({
        everyday: 10,
        school: 8,
        work: 6,
        photo: 8,
        entertainment: 8,
        calls: 8,
        fitness: 4,
        desk: 3,
        mobile: 9,
        mix: 9,
        camera: 7,
        battery: 8,
        power: 7,
        portability: 8,
        display: 8,
        large: 6,
        compact: 6,
        cellular: 9,
        entry: 6,
      }),
      buy: buy.iphone,
    },
    {
      id: "iphone-air",
      name: "iPhone Air",
      chip: "A19 Pro",
      category: "iphone",
      theme: "light",
      kind: "iphone-air",
      tagline: "Impossibly thin.",
      pitch:
        "The iPhone to carry when weight and thinness matter as much as the camera.",
      chooseIf: "You want the lightest iPhone in the lineup and you will pay a bit more for it.",
      price: 999,
      finishes: [
        { name: "Sky Blue", hex: "#c5d6e6" },
        { name: "Light Gold", hex: "#e4d3b8" },
        { name: "Cloud White", hex: "#f3f1ec" },
        { name: "Space Black", hex: "#2a2c30" },
      ],
      specs: [
        ["Chip", "A19 Pro"],
        ["Design", "Thin and light"],
        ["Display", "Super Retina XDR"],
        ["Best for", "Carrying all day"],
      ],
      scores: S({
        everyday: 8,
        school: 7,
        work: 6,
        photo: 8,
        entertainment: 7,
        calls: 8,
        desk: 2,
        mobile: 10,
        mix: 8,
        camera: 8,
        battery: 7,
        power: 7,
        portability: 10,
        display: 8,
        large: 4,
        compact: 10,
        cellular: 9,
        entry: 4,
      }),
      buy: buy.iphone,
    },
    {
      id: "iphone-17-pro",
      name: "iPhone 17 Pro",
      chip: "A19 Pro",
      category: "iphone",
      theme: "dark",
      kind: "iphone-pro",
      tagline: "A pro camera. A pro phone.",
      pitch:
        "The previous Pro, still on sale, for people who want a pro camera system and a lower price than iPhone 18 Pro.",
      chooseIf: "You want a pro iPhone and you’d rather save against the newest model.",
      price: 1099,
      finishes: [
        { name: "Cosmic Orange", hex: "#c4652d" },
        { name: "Deep Blue", hex: "#2d3d55" },
        { name: "Silver", hex: "#d5d6da" },
      ],
      specs: [
        ["Chip", "A19 Pro"],
        ["Camera", "Pro camera system"],
        ["Display", "ProMotion"],
        ["Best for", "Photos and video"],
      ],
      scores: S({
        everyday: 7,
        school: 5,
        work: 6,
        photo: 9,
        entertainment: 8,
        calls: 8,
        desk: 3,
        mobile: 8,
        mix: 8,
        camera: 9,
        battery: 8,
        power: 8,
        portability: 6,
        display: 9,
        large: 7,
        compact: 4,
        cellular: 9,
        entry: 2,
      }),
      buy: buy.iphone,
    },
    {
      id: "iphone-17-pro-max",
      name: "iPhone 17 Pro Max",
      chip: "A19 Pro",
      category: "iphone",
      theme: "dark",
      kind: "iphone-pro",
      tagline: "The biggest 17 Pro.",
      pitch:
        "A large pro iPhone with the longest battery in the 17 Pro pair, at a lower price than iPhone 18 Pro Max.",
      chooseIf: "You want the biggest phone and the previous Pro Max price.",
      price: 1199,
      finishes: [
        { name: "Cosmic Orange", hex: "#c4652d" },
        { name: "Deep Blue", hex: "#2d3d55" },
        { name: "Silver", hex: "#d5d6da" },
      ],
      specs: [
        ["Chip", "A19 Pro"],
        ["Camera", "Pro camera system"],
        ["Display", "Largest 17 Pro display"],
        ["Best for", "Battery and big screen"],
      ],
      scores: S({
        everyday: 6,
        photo: 9,
        work: 6,
        entertainment: 8,
        calls: 8,
        desk: 3,
        mobile: 7,
        mix: 7,
        camera: 9,
        battery: 10,
        power: 8,
        portability: 3,
        display: 9,
        large: 10,
        compact: 2,
        cellular: 9,
        entry: 1,
      }),
      buy: buy.iphone,
    },
    {
      id: "iphone-18-pro",
      name: "iPhone 18 Pro",
      chip: "A20 Pro",
      category: "iphone",
      theme: "dark",
      kind: "iphone-pro",
      tagline: "Pro further.",
      pitch:
        "The newest pro iPhone. A 48MP Fusion camera with variable aperture, A20 Pro, and the longest stride in battery and on-device intelligence.",
      chooseIf: "You want the best camera and the latest pro iPhone, in a size you can still use one-handed.",
      price: 1199,
      finishes: [
        { name: "Black", hex: "#1a1b1e" },
        { name: "Silver", hex: "#d8d8dc" },
        { name: "Glacier", hex: "#d5dde6" },
        { name: "Burgundy", hex: "#6d2c38" },
      ],
      specs: [
        ["Chip", "A20 Pro"],
        ["Camera", "48MP Fusion, variable aperture"],
        ["Video", "Cinematic effects up to 60 fps"],
        ["Best for", "Camera and performance"],
      ],
      scores: S({
        everyday: 8,
        school: 5,
        work: 7,
        photo: 10,
        entertainment: 9,
        calls: 8,
        fitness: 4,
        desk: 3,
        mobile: 8,
        mix: 8,
        camera: 10,
        battery: 9,
        power: 10,
        portability: 6,
        display: 10,
        large: 7,
        compact: 4,
        cellular: 9,
        entry: 1,
      }),
      buy: buy.iphone,
    },
    {
      id: "iphone-18-pro-max",
      name: "iPhone 18 Pro Max",
      chip: "A20 Pro",
      category: "iphone",
      theme: "dark",
      kind: "iphone-pro",
      tagline: "The largest leap in iPhone battery.",
      pitch:
        "Everything in iPhone 18 Pro, with the biggest display and the largest battery-life increase Apple has shipped on iPhone.",
      chooseIf: "You want the newest pro camera and the phone that stays going the longest.",
      price: 1299,
      finishes: [
        { name: "Black", hex: "#1a1b1e" },
        { name: "Silver", hex: "#d8d8dc" },
        { name: "Glacier", hex: "#d5dde6" },
        { name: "Burgundy", hex: "#6d2c38" },
      ],
      specs: [
        ["Chip", "A20 Pro"],
        ["Camera", "48MP Fusion, variable aperture"],
        ["Battery", "Largest gain ever on iPhone"],
        ["Best for", "Big screen and endurance"],
      ],
      scores: S({
        everyday: 7,
        photo: 10,
        work: 6,
        entertainment: 9,
        calls: 8,
        desk: 3,
        mobile: 7,
        mix: 7,
        camera: 10,
        battery: 10,
        power: 10,
        portability: 4,
        display: 10,
        large: 10,
        compact: 2,
        cellular: 9,
      }),
      buy: buy.iphone,
    },
    {
      id: "ipad",
      name: "iPad",
      chip: "A16",
      category: "ipad",
      theme: "light",
      kind: "ipad",
      tagline: "The all-purpose iPad.",
      pitch:
        "For notes, class, streaming, and a first Apple Pencil. The right iPad when the price should stay low.",
      chooseIf: "You want an iPad for school or the couch and you do not need pro apps.",
      price: 449,
      finishes: [
        { name: "Silver", hex: "#d8d8dc" },
        { name: "Blue", hex: "#8eb6d6" },
        { name: "Pink", hex: "#f0c3cb" },
        { name: "Yellow", hex: "#f3e3a4" },
      ],
      specs: [
        ["Chip", "A16"],
        ["Display", "Liquid Retina"],
        ["Pencil", "Apple Pencil (USB-C)"],
        ["Best for", "School and everyday"],
      ],
      scores: S({
        everyday: 8,
        school: 9,
        notes: 9,
        entertainment: 8,
        drawing: 5,
        work: 5,
        photo: 4,
        desk: 5,
        mobile: 8,
        mix: 8,
        pencil: 6,
        display: 6,
        portability: 8,
        battery: 8,
        power: 4,
        large: 4,
        compact: 5,
        cellular: 7,
        entry: 10,
        camera: 4,
      }),
      buy: buy.ipad,
    },
    {
      id: "ipad-mini",
      name: "iPad mini",
      chip: "A17 Pro",
      category: "ipad",
      theme: "light",
      kind: "ipad",
      tagline: "Small enough to go anywhere.",
      pitch:
        "A full iPad that fits in a small bag or a hand. Reading, notes, and Pencil, in the most compact size.",
      chooseIf: "You want an iPad you can hold in one hand.",
      price: 599,
      finishes: [
        { name: "Space Gray", hex: "#6d6e73" },
        { name: "Blue", hex: "#8eb0cc" },
        { name: "Purple", hex: "#c3b4dc" },
        { name: "Starlight", hex: "#e7dccb" },
      ],
      specs: [
        ["Chip", "A17 Pro"],
        ["Display", "8.3-inch Liquid Retina"],
        ["Design", "Ultra portable"],
        ["Best for", "Reading and notes"],
      ],
      scores: S({
        everyday: 7,
        school: 7,
        notes: 8,
        entertainment: 8,
        drawing: 6,
        work: 5,
        desk: 4,
        mobile: 10,
        mix: 8,
        pencil: 6,
        display: 7,
        portability: 10,
        battery: 7,
        power: 5,
        large: 2,
        compact: 10,
        cellular: 7,
        entry: 7,
      }),
      buy: buy.ipad,
    },
    {
      id: "ipad-air-11",
      name: "11-inch iPad Air",
      chip: "M4",
      category: "ipad",
      theme: "light",
      kind: "ipad",
      tagline: "Now supercharged by M4.",
      pitch:
        "The iPad most people should buy. Light, fast, and ready for notes, Pencil, and everyday work.",
      chooseIf: "You want a fast, thin iPad and you do not need the Pro display.",
      price: 749,
      finishes: [
        { name: "Blue", hex: "#8eb4d2" },
        { name: "Purple", hex: "#c2b2da" },
        { name: "Starlight", hex: "#e8dccb" },
        { name: "Space Gray", hex: "#72737a" },
      ],
      specs: [
        ["Chip", "Apple M4"],
        ["Display", "11-inch Liquid Retina"],
        ["Pencil", "Apple Pencil Pro"],
        ["Best for", "Notes, class, and work"],
      ],
      scores: S({
        everyday: 8,
        school: 9,
        notes: 9,
        drawing: 8,
        work: 8,
        photo: 6,
        entertainment: 8,
        film: 4,
        desk: 6,
        mobile: 8,
        mix: 9,
        pencil: 9,
        display: 8,
        power: 7,
        portability: 8,
        battery: 8,
        large: 5,
        compact: 6,
        cellular: 8,
        camera: 5,
        entry: 5,
      }),
      buy: buy.ipad,
    },
    {
      id: "ipad-air-13",
      name: "13-inch iPad Air",
      chip: "M4",
      category: "ipad",
      theme: "light",
      kind: "ipad",
      tagline: "More screen. Still Air.",
      pitch:
        "The larger Air for split view, documents, and drawing when you want room without a Pro price.",
      chooseIf: "You want a big iPad for work or study and M4 is plenty.",
      price: 949,
      finishes: [
        { name: "Blue", hex: "#8eb4d2" },
        { name: "Purple", hex: "#c2b2da" },
        { name: "Starlight", hex: "#e8dccb" },
        { name: "Space Gray", hex: "#72737a" },
      ],
      specs: [
        ["Chip", "Apple M4"],
        ["Display", "13-inch Liquid Retina"],
        ["Pencil", "Apple Pencil Pro"],
        ["Best for", "Documents and drawing"],
      ],
      scores: S({
        everyday: 7,
        school: 8,
        notes: 9,
        drawing: 8,
        work: 8,
        entertainment: 8,
        photo: 6,
        desk: 7,
        mobile: 7,
        mix: 8,
        pencil: 9,
        display: 9,
        power: 7,
        portability: 6,
        battery: 8,
        large: 8,
        compact: 3,
        cellular: 8,
        entry: 3,
      }),
      buy: buy.ipad,
    },
    {
      id: "ipad-pro-11",
      name: "11-inch iPad Pro",
      chip: "M5",
      category: "ipad",
      theme: "dark",
      kind: "ipad",
      tagline: "The ultimate thin iPad.",
      pitch:
        "Pro display, Apple Pencil Pro, and M5 for drawing, editing, and demanding apps on the go.",
      chooseIf: "You draw or edit seriously and you want that power in the smaller Pro.",
      price: 1199,
      finishes: [
        { name: "Silver", hex: "#d5d6da" },
        { name: "Space Black", hex: "#2c2d31" },
      ],
      specs: [
        ["Chip", "Apple M5"],
        ["Display", "11-inch Ultra Retina XDR"],
        ["Pencil", "Apple Pencil Pro"],
        ["Best for", "Pro drawing and apps"],
      ],
      scores: S({
        everyday: 6,
        school: 7,
        notes: 8,
        drawing: 10,
        work: 9,
        photo: 7,
        film: 6,
        entertainment: 8,
        desk: 7,
        mobile: 8,
        mix: 8,
        pencil: 10,
        display: 10,
        power: 9,
        portability: 7,
        battery: 8,
        large: 6,
        compact: 5,
        cellular: 8,
        entry: 2,
      }),
      buy: buy.ipad,
    },
    {
      id: "ipad-pro-13",
      name: "13-inch iPad Pro",
      chip: "M5",
      category: "ipad",
      theme: "dark",
      kind: "ipad",
      tagline: "The largest pro canvas.",
      pitch:
        "The biggest, brightest iPad. For illustration, multi-window work, and people replacing a laptop for creative apps.",
      chooseIf: "Your work is visual and you want the largest iPad display.",
      price: 1499,
      finishes: [
        { name: "Silver", hex: "#d5d6da" },
        { name: "Space Black", hex: "#2c2d31" },
      ],
      specs: [
        ["Chip", "Apple M5"],
        ["Display", "13-inch Ultra Retina XDR"],
        ["Pencil", "Apple Pencil Pro"],
        ["Best for", "Illustration and pro work"],
      ],
      scores: S({
        everyday: 5,
        school: 6,
        notes: 8,
        drawing: 10,
        work: 10,
        photo: 7,
        film: 7,
        desk: 8,
        mobile: 6,
        mix: 7,
        pencil: 10,
        display: 10,
        power: 9,
        portability: 5,
        battery: 8,
        large: 10,
        compact: 2,
        cellular: 8,
        entry: 1,
      }),
      buy: buy.ipad,
    },
    {
      id: "watch-se",
      name: "Apple Watch SE 3",
      chip: "S11",
      category: "watch",
      theme: "light",
      kind: "watch",
      tagline: "Essential health. Essential price.",
      pitch:
        "A first Apple Watch for activity, notifications, and the core health features, at the price most people should start with.",
      chooseIf: "You want Apple Watch essentials and you do not need the new health sensors.",
      price: 249,
      finishes: [
        { name: "Midnight", hex: "#2c3038" },
        { name: "Starlight", hex: "#e6d9c8" },
        { name: "Silver", hex: "#d5d6da" },
      ],
      specs: [
        ["Case", "Aluminum"],
        ["Focus", "Essentials"],
        ["Best for", "A first watch"],
        ["Starts at", "$249"],
      ],
      scores: S({
        everyday: 8,
        fitness: 6,
        health: 6,
        outdoor: 3,
        calls: 5,
        entry: 10,
        battery: 6,
        portability: 8,
        compact: 8,
        cellular: 6,
        display: 6,
        mobile: 10,
        mix: 8,
        desk: 2,
        large: 3,
      }),
      buy: buy.watch,
    },
    {
      id: "watch-s12",
      name: "Apple Watch Series 12",
      chip: "S11",
      category: "watch",
      theme: "light",
      kind: "watch",
      tagline: "The most accurate heart rate sensing in a wearable.",
      pitch:
        "The watch to wear every day. Health Sensing, up to 24 hours of battery, and a readiness score in the size most people want.",
      chooseIf: "Health and daily wear matter, and you are not living on the trail.",
      price: 399,
      finishes: [
        { name: "Dark Bronze", hex: "#6e5340" },
        { name: "Black", hex: "#1c1c1e" },
        { name: "Light Gold", hex: "#d9c4a2" },
        { name: "Space Gray", hex: "#6e6e73" },
      ],
      specs: [
        ["Chip", "S11"],
        ["Health", "Health Sensing System"],
        ["Battery", "Up to 24 hours"],
        ["Best for", "All-day health"],
      ],
      scores: S({
        everyday: 10,
        fitness: 9,
        health: 10,
        outdoor: 6,
        calls: 6,
        battery: 8,
        portability: 8,
        compact: 6,
        cellular: 8,
        display: 7,
        mobile: 10,
        mix: 9,
        desk: 2,
        entry: 5,
        large: 5,
      }),
      buy: buy.watch,
    },
    {
      id: "watch-ultra",
      name: "Apple Watch Ultra 4",
      chip: "S11",
      category: "watch",
      theme: "dark",
      kind: "ultra",
      tagline: "A battery you can’t outrun.",
      pitch:
        "The endurance watch. Up to 45 hours of outdoor workout tracking and up to 50 hours of everyday battery, in a tougher titanium case.",
      chooseIf: "You train outside for hours, or you want the brightest, toughest watch.",
      price: 799,
      finishes: [
        { name: "Natural Titanium", hex: "#c2b8aa" },
        { name: "Black Titanium", hex: "#2a2a2c" },
      ],
      specs: [
        ["Chip", "S11"],
        ["Case", "Titanium, 49mm"],
        ["Battery", "Up to 50 hours everyday"],
        ["Best for", "Endurance and outdoors"],
      ],
      scores: S({
        everyday: 7,
        fitness: 10,
        health: 9,
        outdoor: 10,
        calls: 5,
        battery: 10,
        portability: 6,
        compact: 3,
        cellular: 9,
        display: 8,
        mobile: 10,
        mix: 8,
        desk: 2,
        large: 8,
        entry: 1,
      }),
      buy: buy.watch,
    },
    {
      id: "airpods-pro",
      name: "AirPods Pro 3",
      chip: "In-ear",
      category: "airpods",
      theme: "light",
      kind: "airpods",
      tagline: "The best in-ear noise cancellation.",
      pitch:
        "AirPods Pro 3 when you want silicone tips, the quietest commute, clearer calls, and heart rate on a workout.",
      chooseIf: "You want the strongest in-ear noise cancellation and a secure fit for workouts.",
      price: 249,
      finishes: [{ name: "White", hex: "#f4f4f2" }],
      specs: [
        ["Design", "In-ear with silicone tips"],
        ["Audio", "Best in-ear Active Noise Cancellation"],
        ["Health", "Heart rate sensing during workouts"],
        ["Battery", "Up to 8 hours of listening"],
      ],
      scores: S({
        everyday: 8,
        calls: 9,
        entertainment: 9,
        anc: 10,
        compact: 8,
        battery: 9,
        portability: 10,
        mobile: 10,
        mix: 9,
        desk: 6,
        entry: 4,
        fitness: 8,
        overear: 1,
      }),
      buy: "https://www.apple.com/shop/buy-airpods/airpods-pro-3",
    },
    {
      id: "airpods-4",
      name: "AirPods 4",
      chip: "Open-ear",
      category: "airpods",
      theme: "light",
      kind: "airpods",
      tagline: "Open-ear. Open price.",
      pitch:
        "The less expensive open-ear AirPods for music and calls when noise cancellation is not the point.",
      chooseIf: "You want AirPods for calls and music and you want the lowest price.",
      price: 129,
      finishes: [{ name: "White", hex: "#f4f4f2" }],
      specs: [
        ["Design", "Open-ear"],
        ["Audio", "Personalized Spatial Audio"],
        ["Case", "Wireless charging available"],
        ["Best for", "Calls and everyday listening"],
      ],
      scores: S({
        everyday: 7,
        calls: 8,
        entertainment: 7,
        anc: 4,
        compact: 9,
        entry: 10,
        portability: 10,
        battery: 7,
        mobile: 10,
        mix: 9,
        desk: 4,
        overear: 1,
        fitness: 4,
      }),
      buy: buy.airpods,
    },
    {
      id: "airpods-5",
      name: "AirPods 5",
      chip: "Open-ear",
      category: "airpods",
      theme: "light",
      kind: "airpods",
      tagline: "The best noise cancellation in an open-ear design.",
      pitch:
        "Open-ear AirPods with stronger noise cancellation than AirPods 4, a volume swipe on the stem, and the case most people should get.",
      chooseIf: "You want open-ear AirPods, without silicone tips, for calls and everyday listening.",
      price: 179,
      finishes: [{ name: "White", hex: "#f7f7f5" }],
      specs: [
        ["Design", "Open-ear with ANC"],
        ["Audio", "Multiport acoustics, Adaptive EQ"],
        ["Control", "Volume swipe on the stem"],
        ["Best for", "Travel, focus, and calls"],
      ],
      scores: S({
        everyday: 8,
        calls: 9,
        entertainment: 9,
        anc: 9,
        compact: 8,
        battery: 8,
        portability: 10,
        mobile: 10,
        mix: 9,
        desk: 5,
        entry: 7,
        fitness: 5,
        overear: 2,
      }),
      buy: buy.airpods,
    },
    {
      id: "airpods-max",
      name: "AirPods Max",
      chip: "Over-ear",
      category: "airpods",
      theme: "dark",
      kind: "airpods-max",
      tagline: "High fidelity. Over ear.",
      pitch:
        "Over-ear listening for a desk or a living room, when you want the most immersive sound Apple makes in headphones.",
      chooseIf: "You listen for long sessions at home and you want over-ear cushions.",
      price: 549,
      finishes: [
        { name: "Midnight", hex: "#2c3140" },
        { name: "Starlight", hex: "#e4d7c6" },
        { name: "Blue", hex: "#8aa4c8" },
        { name: "Orange", hex: "#e08a4f" },
        { name: "Purple", hex: "#b7a6d4" },
      ],
      specs: [
        ["Design", "Over-ear"],
        ["Audio", "High-fidelity"],
        ["Best for", "Home listening"],
        ["Starts at", "$549"],
      ],
      scores: S({
        everyday: 5,
        calls: 7,
        entertainment: 10,
        anc: 8,
        overear: 10,
        compact: 1,
        portability: 4,
        battery: 7,
        desk: 8,
        mobile: 5,
        mix: 6,
        entry: 1,
        fitness: 1,
      }),
      buy: buy.airpods,
    },
    {
      id: "iphone-duo",
      name: "iPhone Duo",
      chip: "Coming soon",
      category: "iphone",
      theme: "dark",
      kind: "iphone",
      tagline: "Hello, hello.",
      pitch: "A new iPhone arriving this month. Pre-order opens October 16.",
      chooseIf: "",
      price: null,
      recommendable: false,
      coming: "Pre-order starting 5:00 a.m. PT on 10.16. Available starting 10.23.",
      finishes: [{ name: "Silver", hex: "#e4e4e6" }],
      specs: [],
      scores: S({}),
      buy: "https://www.apple.com/",
    },
  ];

  // Fix the accidental string replace on orange if it survived — set explicitly.
  const max = products.find((p) => p.id === "airpods-max");
  max.finishes = [
    { name: "Midnight", hex: "#2c3140" },
    { name: "Starlight", hex: "#e4d7c6" },
    { name: "Blue", hex: "#8aa4c8" },
    { name: "Orange", hex: "#e08a4f" },
    { name: "Purple", hex: "#b7a6d4" },
  ];

  const catalogs = {
    mac: [
      "macbook-neo",
      "mba-13",
      "mba-15",
      "mbp-14",
      "mbp-14-pro",
      "mbp-16-pro",
      "mbp-16-max",
      "imac",
      "mac-mini",
      "mac-mini-pro",
      "mac-studio",
    ],
    ipad: ["ipad", "ipad-mini", "ipad-air-11", "ipad-air-13", "ipad-pro-11", "ipad-pro-13"],
    iphone: [
      "iphone-18-pro",
      "iphone-18-pro-max",
      "iphone-air",
      "iphone-17-pro",
      "iphone-17-pro-max",
      "iphone-17",
      "iphone-17e",
    ],
    watch: ["watch-s12", "watch-ultra", "watch-se"],
    airpods: ["airpods-pro", "airpods-5", "airpods-4", "airpods-max"],
  };

  function opt(id, title, detail, weights) {
    return { id, title, detail, weights };
  }

  const steps = {
    category: {
      key: "category",
      type: "single",
      kicker: "Product Finder",
      title: "What are you looking for?",
      detail: "If you’re not sure, we’ll look across the lineup.",
      options: [
        opt("mac", "A computer", "MacBook, iMac, Mac mini, Mac Studio", {}),
        opt("iphone", "An iPhone", "Everyday, Air, and Pro models", {}),
        opt("ipad", "An iPad", "Notes, class, drawing, and pro apps", {}),
        opt("watch", "An Apple Watch", "Health, fitness, and everyday wear", {}),
        opt("airpods", "AirPods", "Music, calls, and quiet", {}),
        opt("any", "I’m not sure", "Recommend anything that fits", {}),
      ],
    },
    "use-mac": {
      key: "use",
      type: "single",
      kicker: "Mac",
      title: "What will you do most?",
      detail: "Pick the work that shows up on a normal week.",
      options: [
        opt("school", "School and everyday", "Classes, writing, browsing, streaming.", { school: 1, everyday: 0.45, notes: 0.25 }),
        opt("work", "Work and multitasking", "Documents, mail, meetings, spreadsheets.", { work: 1, everyday: 0.2 }),
        opt("photo", "Photo and video editing", "Libraries, grades, short films, social cuts.", { photo: 1, film: 0.35 }),
        opt("code", "Software development", "Projects, builds, local servers, lots of tools.", { code: 1, work: 0.35, power: 0.25 }),
        opt("film", "Film, 3D, or music production", "Long timelines, renders, and heavy exports.", { film: 1, power: 0.55, photo: 0.2 }),
      ],
    },
    "use-iphone": {
      key: "use",
      type: "single",
      kicker: "iPhone",
      title: "What kind of phone do you need?",
      detail: "We’ll stay inside the current iPhone lineup.",
      options: [
        opt("day", "An everyday phone", "Messages, maps, photos, and the day-to-day.", { everyday: 1, calls: 0.25, entertainment: 0.2 }),
        opt("photos", "The best photos and video", "Camera first. Everything else second.", { camera: 1, photo: 0.85 }),
        opt("travel", "Long days away from a charger", "Battery has to last.", { battery: 1, mobile: 0.35 }),
        opt("small", "Something lighter", "Thin, compact, easy to live with.", { compact: 1, portability: 0.7 }),
        opt("big", "The biggest screen", "Reading, video, and a larger camera phone.", { large: 1, display: 0.45, battery: 0.25 }),
      ],
    },
    "use-ipad": {
      key: "use",
      type: "single",
      kicker: "iPad",
      title: "What will you use iPad for?",
      detail: "One primary job is enough.",
      options: [
        opt("notes", "Notes and studying", "Class, reading, and handwritten notes.", { notes: 1, school: 0.7 }),
        opt("draw", "Drawing and design", "Pencil, illustration, and visual work.", { drawing: 1, pencil: 0.7, display: 0.25 }),
        opt("work", "Light work instead of a laptop", "Documents, mail, and multitasking.", { work: 1, notes: 0.3 }),
        opt("watch", "Entertainment", "Shows, games, and the couch.", { entertainment: 1, everyday: 0.3 }),
        opt("pro", "Pro apps on the go", "Editing, design tools, and heavier apps.", { power: 1, drawing: 0.4, film: 0.35, work: 0.3 }),
      ],
    },
    "use-watch": {
      key: "use",
      type: "single",
      kicker: "Apple Watch",
      title: "How will you wear it?",
      detail: "This decides SE, Series 12, or Ultra.",
      options: [
        opt("daily", "All day, for health and notifications", "The watch you forget you’re wearing.", { everyday: 1, health: 0.75 }),
        opt("train", "Workouts and running", "Training is the main reason.", { fitness: 1, health: 0.45 }),
        opt("wild", "Trails, water, and long days out", "Battery and toughness come first.", { outdoor: 1, fitness: 0.45, battery: 0.45 }),
        opt("first", "An affordable first watch", "The essentials, without the flagship price.", { entry: 1, everyday: 0.45 }),
      ],
    },
    "use-airpods": {
      key: "use",
      type: "single",
      kicker: "AirPods",
      title: "How do you listen?",
      detail: "Open-ear for the day, or over-ear for home.",
      options: [
        opt("calls", "Music and calls all day", "In and out of pockets, on and off calls.", { calls: 1, everyday: 0.55, entertainment: 0.35 }),
        opt("focus", "Focus, travel, and noise", "You want the world turned down.", { anc: 1, calls: 0.3 }),
        opt("home", "Long sessions at home", "Over-ear, at a desk or on the couch.", { overear: 1, entertainment: 0.75, desk: 0.35 }),
      ],
    },
    "use-any": {
      key: "use",
      type: "single",
      kicker: "Across the lineup",
      title: "What should it help you do?",
      detail: "We’ll match a Mac, iPhone, iPad, Watch, or AirPods.",
      options: [
        opt("day", "Get through the day", "Messages, browsing, photos, the usual.", { everyday: 1, calls: 0.15 }),
        opt("school", "School or studying", "Notes, research, and classes.", { school: 1, notes: 0.55 }),
        opt("work", "Work", "Documents, meetings, and real multitasking.", { work: 1, code: 0.2 }),
        opt("photos", "Take and edit photos", "Camera first.", { photo: 1, camera: 0.8 }),
        opt("pro", "Pro creative work", "Film, design, 3D, or heavy projects.", { film: 1, power: 0.6 }),
        opt("fitness", "Fitness and health", "Workouts, heart rate, and daily movement.", { fitness: 1, health: 0.8 }),
        opt("audio", "Music, calls, and quiet", "Listening is the whole point.", { anc: 0.7, calls: 0.45, entertainment: 0.45 }),
      ],
    },
    "place-default": {
      key: "place",
      type: "single",
      kicker: "Where it lives",
      title: "Where will you use it?",
      detail: "A desktop is a joy at a desk and a burden everywhere else.",
      options: [
        opt("desk", "Mostly at a desk", "A desktop is fine. I don’t need to carry it.", { desk: 1 }),
        opt("mobile", "Mostly with me", "It has to travel.", { mobile: 1, portability: 0.4 }),
        opt("mix", "A mix of both", "Serious time at a desk, and it still comes along.", { mix: 1 }),
      ],
    },
    "place-watch": {
      key: "place",
      type: "single",
      kicker: "Apple Watch",
      title: "Where does it need to keep up?",
      detail: "This nudges size, battery, and toughness.",
      options: [
        opt("city", "Around town", "Office, errands, everyday wear.", { compact: 0.7, everyday: 0.4 }),
        opt("sport", "In training", "Gyms, runs, and regular workouts.", { fitness: 0.8 }),
        opt("wild", "Outside for hours", "Trails, travel days, and long battery.", { outdoor: 1, battery: 0.45 }),
      ],
    },
    "place-airpods": {
      key: "place",
      type: "single",
      kicker: "AirPods",
      title: "Where do you listen most?",
      detail: "Commute, desk, or both.",
      options: [
        opt("commute", "On the move", "Transit, walks, and pockets.", { mobile: 1, portability: 0.5, compact: 0.35 }),
        opt("desk", "At a desk", "Long sessions in one place.", { desk: 1, overear: 0.35 }),
        opt("both", "Wherever I am", "Home and away.", { mix: 1, portability: 0.3 }),
      ],
    },
    "priority-mac": {
      key: "priority",
      type: "single",
      kicker: "What matters",
      title: "What should we optimize for?",
      detail: "One priority. We’ll use the others as tie-breakers.",
      options: [
        opt("value", "Keep the price down", "The capable choice, not the expensive one.", { value: 1 }),
        opt("power", "Performance", "Faster chips for heavier work.", { power: 1 }),
        opt("battery", "Battery life", "Unplugged for as long as possible.", { battery: 1 }),
        opt("portability", "Easy to carry", "Weight and thickness.", { portability: 1, compact: 0.45 }),
        opt("display", "The display", "Size, sharpness, and color.", { display: 1, large: 0.3 }),
      ],
    },
    "priority-iphone": {
      key: "priority",
      type: "single",
      kicker: "What matters",
      title: "What should we optimize for?",
      detail: "We’ll pick the iPhone that wins on this.",
      options: [
        opt("value", "Keep the price down", "Spend less. Keep the parts you will notice.", { value: 1 }),
        opt("camera", "Camera", "Photos and video above everything.", { camera: 1 }),
        opt("battery", "Battery life", "Fewer afternoons at 10 percent.", { battery: 1 }),
        opt("portability", "Light and thin", "The phone you forget is in your pocket.", { portability: 1, compact: 0.6 }),
        opt("display", "The display", "Brightness, smoothness, and size.", { display: 1, large: 0.25 }),
      ],
    },
    "priority-ipad": {
      key: "priority",
      type: "single",
      kicker: "What matters",
      title: "What should we optimize for?",
      detail: "Pencil, screen, or the price.",
      options: [
        opt("value", "Keep the price down", "A great iPad, not the most iPad.", { value: 1 }),
        opt("pencil", "Apple Pencil", "Writing and drawing are the point.", { pencil: 1, drawing: 0.45 }),
        opt("display", "The display", "Size and quality of the screen.", { display: 1, large: 0.35 }),
        opt("portability", "Easy to carry", "The one that leaves the house.", { portability: 1, compact: 0.5 }),
        opt("power", "Performance", "Heavier apps and pro work.", { power: 1 }),
      ],
    },
    "priority-watch": {
      key: "priority",
      type: "single",
      kicker: "What matters",
      title: "What should we optimize for?",
      detail: "Series 12 is the health pick. Ultra is the endurance pick.",
      options: [
        opt("value", "Keep the price down", "Start with the essentials.", { value: 1 }),
        opt("health", "Health sensing", "Heart rate, readiness, daily insight.", { health: 1 }),
        opt("battery", "Battery life", "More hours between charges.", { battery: 1 }),
        opt("outdoor", "The outdoors", "A tougher case and a longer trail.", { outdoor: 1 }),
        opt("compact", "Light everyday wear", "Comfort from morning to night.", { compact: 1 }),
      ],
    },
    "priority-airpods": {
      key: "priority",
      type: "single",
      kicker: "What matters",
      title: "What should we optimize for?",
      detail: "Price, quiet, or the way they feel.",
      options: [
        opt("value", "Keep the price down", "Good sound without the flagship case.", { value: 1 }),
        opt("anc", "Noise cancellation", "Turn a commute down.", { anc: 1 }),
        opt("sound", "Sound quality", "The most immersive listening.", { entertainment: 1 }),
        opt("calls", "Calls", "Your voice, clearly.", { calls: 1 }),
        opt("compact", "The smallest fit", "Light in the ear and the pocket.", { compact: 1 }),
      ],
    },
    "priority-any": {
      key: "priority",
      type: "single",
      kicker: "What matters",
      title: "What should we optimize for?",
      detail: "One thing. We’ll keep the rest in mind.",
      options: [
        opt("value", "Keep the price down", "The right product, not the dearest one.", { value: 1 }),
        opt("camera", "Camera", "Photos and video.", { camera: 1 }),
        opt("battery", "Battery life", "Time away from a charger.", { battery: 1 }),
        opt("power", "Performance", "For real work or creative projects.", { power: 1 }),
        opt("portability", "Easy to carry", "Light, thin, pocketable.", { portability: 1, compact: 0.4 }),
        opt("display", "The display", "A screen you want to look at.", { display: 1 }),
        opt("health", "Health features", "Sensing, fitness, and daily stats.", { health: 1, fitness: 0.4 }),
      ],
    },
    "extras-mac": {
      key: "extras",
      type: "multi",
      kicker: "Anything else",
      title: "Any must-haves?",
      detail: "Optional. Choose any that would rule a product out.",
      options: [
        opt("large", "The largest screen", "More space to work.", { large: 1, display: 0.3 }),
        opt("light", "As light as possible", "It lives in a bag.", { compact: 1, portability: 0.5 }),
        opt("ports", "Desktop power and ports", "A machine that stays put and works hard.", { ports: 1, desk: 0.45, power: 0.25 }),
      ],
    },
    "extras-iphone": {
      key: "extras",
      type: "multi",
      kicker: "Anything else",
      title: "Any must-haves?",
      detail: "Optional. Skip this if nothing here is essential.",
      options: [
        opt("large", "Largest phone", "More screen, more battery.", { large: 1, battery: 0.25 }),
        opt("small", "Most compact", "Easier in a pocket.", { compact: 1, portability: 0.4 }),
        opt("battery", "Longest battery", "Charge less often.", { battery: 1 }),
      ],
    },
    "extras-ipad": {
      key: "extras",
      type: "multi",
      kicker: "Anything else",
      title: "Any must-haves?",
      detail: "Optional.",
      options: [
        opt("pencil", "Apple Pencil is essential", "Notes or drawing every day.", { pencil: 1, drawing: 0.4 }),
        opt("cell", "Cellular, not only Wi-Fi", "A connection away from your phone.", { cellular: 1 }),
        opt("large", "Largest canvas", "The biggest iPad display.", { large: 1, display: 0.3 }),
        opt("small", "Compact enough for a small bag", "mini, or close to it.", { compact: 1, portability: 0.4 }),
      ],
    },
    "extras-watch": {
      key: "extras",
      type: "multi",
      kicker: "Anything else",
      title: "Any must-haves?",
      detail: "Optional.",
      options: [
        opt("cell", "Cellular, so the phone can stay home", "Calls and maps from the wrist.", { cellular: 1 }),
        opt("rugged", "Built for the outdoors", "A tougher case.", { outdoor: 1 }),
        opt("light", "Light enough for all-day wear", "Comfort over ruggedness.", { compact: 1 }),
      ],
    },
    "extras-airpods": {
      key: "extras",
      type: "multi",
      kicker: "Anything else",
      title: "Any must-haves?",
      detail: "Optional.",
      options: [
        opt("anc", "The best noise cancellation", "Quiet matters.", { anc: 1 }),
        opt("over", "Over-ear, for home", "Cushions, not stems.", { overear: 1 }),
        opt("tiny", "The smallest fit", "Easy to pocket.", { compact: 1, portability: 0.3 }),
      ],
    },
    "extras-any": {
      key: "extras",
      type: "multi",
      kicker: "Anything else",
      title: "Any must-haves?",
      detail: "Optional. These apply across the lineup.",
      options: [
        opt("light", "Easy to carry", "Light and compact.", { compact: 1, portability: 0.4 }),
        opt("big", "A large display", "More screen.", { large: 1, display: 0.35 }),
        opt("cell", "Cellular", "A connection of its own.", { cellular: 1 }),
        opt("pencil", "Apple Pencil", "Handwriting or drawing.", { pencil: 1 }),
        opt("quiet", "Noise cancellation", "Headphones that get quiet.", { anc: 1 }),
        opt("power", "Serious performance", "A faster chip and more ports.", { power: 1, ports: 0.4 }),
      ],
    },
  };

  function budget(id, title, detail, min, max, soft) {
    return { id, title, detail, min, max, soft: !!soft, weights: {} };
  }

  steps["budget-mac"] = {
    key: "budget",
    type: "single",
    kicker: "Budget",
    title: "What do you want to spend?",
    detail: "U.S. starting prices. More storage and memory cost more.",
    options: [
      budget("lt", "Under $800", "MacBook Neo territory.", 0, 800),
      budget("mid", "$800 to $1,600", "Mac mini, iMac, and MacBook Air.", 800, 1600),
      budget("high", "$1,600 to $2,600", "MacBook Pro and Mac mini with M5 Pro.", 1600, 2600),
      budget("top", "$2,600 and above", "16-inch MacBook Pro.", 2600, null),
      budget("best", "Show me the best fit", "We’ll weigh value against what you asked for.", 0, null, true),
    ],
  };
  steps["budget-iphone"] = {
    key: "budget",
    type: "single",
    kicker: "Budget",
    title: "What do you want to spend?",
    detail: "U.S. starting prices, before trade-in.",
    options: [
      budget("lt", "Under $700", "iPhone 17e.", 0, 700),
      budget("mid", "$700 to $1,000", "iPhone 17 and iPhone Air.", 700, 1000),
      budget("high", "$1,000 to $1,300", "Pro and Pro Max.", 1000, 1300),
      budget("best", "Show me the best fit", "Camera, battery, or the phone most people should buy.", 0, null, true),
    ],
  };
  steps["budget-ipad"] = {
    key: "budget",
    type: "single",
    kicker: "Budget",
    title: "What do you want to spend?",
    detail: "U.S. starting prices for Wi-Fi models.",
    options: [
      budget("lt", "Under $600", "iPad and iPad mini.", 0, 600),
      budget("mid", "$600 to $1,000", "iPad Air.", 600, 1000),
      budget("high", "$1,000 to $1,600", "iPad Pro.", 1000, 1600),
      budget("best", "Show me the best fit", "We’ll pick the iPad that matches the work.", 0, null, true),
    ],
  };
  steps["budget-watch"] = {
    key: "budget",
    type: "single",
    kicker: "Budget",
    title: "What do you want to spend?",
    detail: "U.S. starting prices for GPS models.",
    options: [
      budget("lt", "Under $300", "Apple Watch SE 3.", 0, 300),
      budget("mid", "$300 to $550", "Apple Watch Series 12.", 300, 550),
      budget("high", "$550 and above", "Apple Watch Ultra 4.", 550, null),
      budget("best", "Show me the best fit", "Health, fitness, or the outdoors.", 0, null, true),
    ],
  };
  steps["budget-airpods"] = {
    key: "budget",
    type: "single",
    kicker: "Budget",
    title: "What do you want to spend?",
    detail: "U.S. starting prices.",
    options: [
      budget("lt", "Under $150", "AirPods 4.", 0, 150),
      budget("mid", "$150 to $300", "AirPods 5 and AirPods Pro 3.", 150, 300),
      budget("high", "$300 and above", "AirPods Max.", 300, null),
      budget("best", "Show me the best fit", "Day to day, or listening at home.", 0, null, true),
    ],
  };
  steps["budget-any"] = {
    key: "budget",
    type: "single",
    kicker: "Budget",
    title: "What do you want to spend?",
    detail: "We’ll stay near this, across every product family.",
    options: [
      budget("lt", "Under $500", "iPad, Apple Watch SE, AirPods.", 0, 500),
      budget("mid", "$500 to $1,200", "iPhone, iPad Air, MacBook Neo, Watch.", 500, 1200),
      budget("high", "$1,200 to $2,500", "MacBook Air, MacBook Pro, iPad Pro.", 1200, 2500),
      budget("top", "$2,500 and above", "Pro desktops and high-end MacBook Pro.", 2500, null),
      budget("best", "Show me the best fit", "The product that matches, with an eye on price.", 0, null, true),
    ],
  };

  const flowMap = {
    mac: ["category", "use-mac", "place-default", "priority-mac", "budget-mac", "extras-mac"],
    iphone: ["category", "use-iphone", "priority-iphone", "budget-iphone", "extras-iphone"],
    ipad: ["category", "use-ipad", "priority-ipad", "budget-ipad", "extras-ipad"],
    watch: ["category", "use-watch", "place-watch", "priority-watch", "budget-watch", "extras-watch"],
    airpods: ["category", "use-airpods", "priority-airpods", "budget-airpods", "extras-airpods"],
    any: ["category", "use-any", "priority-any", "budget-any", "extras-any"],
  };

  function getFlow(answers) {
    const cat = answers && answers.category ? answers.category : "any";
    const ids = flowMap[cat] || flowMap.any;
    return ids.map((id) => steps[id]);
  }

  const homeTiles = [
    {
      wide: true,
      theme: "dark",
      kicker: "iPhone 18 Pro",
      title: "Pro further.",
      productId: "iphone-18-pro",
      start: "iphone",
      background:
        "radial-gradient(120% 80% at 50% 100%, #5a2433 0%, #14080c 42%, #000 70%)",
    },
    {
      theme: "light",
      kicker: "MacBook Air",
      title: "Now with M5.",
      productId: "mba-13",
      start: "mac",
      background: "linear-gradient(180deg, #f5f5f7 0%, #e7e7ed 100%)",
    },
    {
      theme: "dark",
      kicker: "Apple Watch Series 12",
      title: "The most accurate heart rate sensing in a wearable.",
      productId: "watch-s12",
      start: "watch",
      background: "radial-gradient(90% 80% at 50% 100%, #6a4b34 0%, #1a120d 45%, #000 72%)",
    },
    {
      theme: "light",
      kicker: "iPad Air",
      title: "Light. Fast. Ready.",
      productId: "ipad-air-11",
      start: "ipad",
      background: "linear-gradient(180deg, #fbfbfd 0%, #e4e4ea 100%)",
    },
    {
      theme: "light",
      kicker: "Mac mini",
      title: "Now with M6 and M5 Pro.",
      productId: "mac-mini",
      start: "mac",
      background: "linear-gradient(180deg, #fafafa 0%, #dcdce2 100%)",
    },
    {
      wide: true,
      theme: "light",
      kicker: "AirPods Pro 3",
      title: "The best in-ear noise cancellation.",
      productId: "airpods-pro",
      start: "airpods",
      background: "linear-gradient(180deg, #f5f5f7 0%, #e8e8ed 100%)",
    },
  ];

  const tvProducts = [
    {
      name: "Apple TV 4K",
      detail: "The streaming box for a TV you already own.",
      price: "From $129",
      href: "https://www.apple.com/apple-tv-4k/",
    },
    {
      name: "HomePod mini",
      detail: "Room-filling sound in a compact speaker.",
      price: "From $99",
      href: "https://www.apple.com/homepod-mini/",
    },
  ];

  const services = [
    { name: "Apple TV+", detail: "Original shows and films.", href: "https://www.apple.com/apple-tv-plus/" },
    { name: "Apple Music", detail: "Every song, in Spatial Audio.", href: "https://www.apple.com/apple-music/" },
    { name: "Apple Arcade", detail: "Games without ads or in-app purchases.", href: "https://www.apple.com/apple-arcade/" },
    { name: "Apple Fitness+", detail: "Workouts for Apple Watch.", href: "https://www.apple.com/apple-fitness-plus/" },
    { name: "Apple News+", detail: "Magazines and leading newspapers.", href: "https://www.apple.com/apple-news/" },
    { name: "iCloud+", detail: "Storage, photos, and private relay.", href: "https://www.apple.com/icloud/" },
  ];

  const accessories = [
    { name: "Apple Pencil", detail: "For notes and drawing on iPad.", href: "https://www.apple.com/apple-pencil/" },
    { name: "Magic Keyboard", detail: "For iPad and for Mac.", href: "https://www.apple.com/shop/accessories" },
    { name: "AirTag", detail: "Keep track of what you misplace.", href: "https://www.apple.com/airtag/" },
    { name: "MagSafe", detail: "Chargers and cases that snap on.", href: "https://www.apple.com/shop/accessories" },
  ];

  const photos = {
    "macbook-neo": "images/macbook-neo.png",
    "mba-13": "images/macbook-air.png",
    "mba-15": "images/macbook-air.png",
    "mbp-14": "images/macbook-pro.png",
    "mbp-14-pro": "images/macbook-pro.png",
    "mbp-16-pro": "images/macbook-pro.png",
    "mbp-16-max": "images/macbook-pro.png",
    imac: "images/imac.png",
    "mac-mini": "images/mac-mini.png",
    "mac-mini-pro": "images/mac-mini.png",
    "mac-studio": "images/mac-studio.png",
    "iphone-18-pro": "images/iphone-18-pro.png",
    "iphone-18-pro-max": "images/iphone-18-pro-max.png",
    "iphone-17-pro": "images/iphone-17.png",
    "iphone-17-pro-max": "images/iphone-17.png",
    "iphone-air": "images/iphone-air.png",
    "iphone-17": "images/iphone-17.png",
    "iphone-17e": "images/iphone-17e.png",
    ipad: "images/ipad.png",
    "ipad-mini": "images/ipad-mini.png",
    "ipad-air-11": "images/ipad-air.png",
    "ipad-air-13": "images/ipad-air.png",
    "ipad-pro-11": "images/ipad-pro.png",
    "ipad-pro-13": "images/ipad-pro.png",
    "watch-s12": "images/watch-s12.png",
    "watch-se": "images/watch-se.png",
    "watch-ultra": "images/watch-ultra.png",
    "airpods-4": "images/airpods-4.png",
    "airpods-5": "images/airpods-5.png",
    "airpods-pro": "images/airpods-pro.png",
    "airpods-max": "images/airpods-max.png",
  };
  products.forEach(function (product) {
    if (photos[product.id]) product.photo = photos[product.id];
  });

  window.FinderData = {
    products,
    catalogs,
    getFlow,
    homeTiles,
    tvProducts,
    services,
    accessories,
    byId(id) {
      return products.find((p) => p.id === id) || null;
    },
  };
})();
